export const GET_SOCIOS = 'GET_SOCIOS';
export const GET_PRESTAMO = 'GET_PRESTAMO';
export const POST_PRESTAMO = "POST_PRESTAMO";
export const DELETE_PRESTAMO = "DELETE_PRESTAMO";

export const GET_HABITACIONES = "GET_HABITACIONES";
export const GET_REGISTRO_ESTADIA = "GET_REGISTRO_ESTADIA";
export const POST_HABITACION = "POST_HABITACION";
export const POST_REGISTRO_ESTADIA = "POST_REGISTRO_ESTADIA";
export const PUT_HABITACION_ESTADO = "PUT_HABITACION_ESTADO";
export const PUT_REGISTRO_ESTADIA_SALIDA = "PUT_REGISTRO_ESTADIA_SALIDA";